server:
  port: 4040
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
zuul:
  routes:
    api-a:
      path: /feign/**
      serviceId: feign
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 3000